160-feature/animal module
cieslarmichal/faker-cxx pull request #176
Opened 2023-10-04 14:05 UTC by Globostofo

Took data from [faker-js](https://github.com/faker-js/faker)

Added animals:
- bears
- birds
- cats
- cetaceans
- cows
- crocodilia
- dogs
- fishes
- horses
- insects
- lions
- rabbits
- rodents
- snakes
- types (generates a random string from the previous animal)

2023-10-04 14:25 UTC, cieslarmichal commented on include/faker-cxx/Animal.h
> +    static std::string bear();
Please add documentation to each method like in other classes.

2023-10-04 14:25 UTC, cieslarmichal requested changes
Good job, left one comment :)

2023-10-05 10:14 UTC, Globostofo commented
Oops, I forgot documentation.

It's good now, I added it :)

2023-10-05 11:57 UTC, cieslarmichal commented
I see the branch is out of date, could you update it please?

2023-10-05 12:37 UTC, cieslarmichal approved these changes

2023-10-05 12:45 UTC, merged