Add location addresses data from Ukraine
cieslarmichal/faker-cxx pull request #339
Opened 2023-11-25 16:22 UTC by Pokulita

2023-11-25 18:18 UTC, cieslarmichal requested changes
Hello, well you need to define actual addresses in location module, modules/location/data and location/Location.cpp and location/LocationTest.cpp like any other countries

2023-11-25 20:22 UTC, Pokulita commented
Sure, i will do it. Thanks for the feedback

2023-12-02 19:20 UTC, cieslarmichal requested changes

2023-12-02 19:20 UTC, cieslarmichal commented on src/modules/location/LocationTest.cpp
> +    {AddressCountry::Ukraine, "shouldGenerateRussianAddress"},
it should be "shouldGenerateUkrainianAddress

2023-12-02 19:22 UTC, cieslarmichal commented
Please fix compilation error and one typo I mentioned in comments.
Also please give a star to the repository to make it more popular :fire:

2023-12-02 20:00 UTC, cieslarmichal approved these changes

2023-12-02 20:19 UTC, cieslarmichal requested changes

2023-12-02 20:19 UTC, cieslarmichal commented on src/modules/location/LocationTest.cpp
> +                                        return generatedStreetAddress.find(streetName) != std::string::npos;
it can be either street name or first name or last name :)

2023-12-02 20:19 UTC, cieslarmichal commented on src/modules/location/LocationTest.cpp
> +                                        return generatedStreetAddress.find(streetName) != std::string::npos;
thus tests are failing

2023-12-06 20:05 UTC, Pokulita commented
Sorry, I will finish it tomorrow

2023-12-10 21:27 UTC, cieslarmichal commented
I will close the PR after 3 days from now if not updated.

2023-12-13 19:22 UTC, closed without merging