test: date module testcase
cieslarmichal/faker-cxx pull request #848
Opened 2024-08-16 22:18 UTC by 00thirdeye00

* testcase added to date module for codecov

Fixes: #807

2024-08-18 21:55 UTC, 00thirdeye00 commented
@cieslarmichal I do not get any issues when built, do you have any idea what linked issue is this?

2024-08-18 22:18 UTC, cieslarmichal approved these changes

2024-08-18 22:19 UTC, cieslarmichal requested changes
Well, gcc complains about linking error, we cannot merge that in the current state

2024-08-19 20:10 UTC, cieslarmichal commented
I fixed date module codecov here: https://github.com/cieslarmichal/faker-cxx/pull/849 closing this one

2024-08-19 20:10 UTC, closed without merging