added continents module
cieslarmichal/faker-cxx pull request #984
Opened 2024-11-16 15:18 UTC by charan-003

added module for continents and data

2024-11-16 16:39 UTC, cieslarmichal requested changes

2024-11-16 16:39 UTC, cieslarmichal commented on src/modules/location.cpp
> +        case faker::Locale::en_GB:
Why did you add faker prefix? Its all in faker namespace so no need

2024-11-16 23:12 UTC, cieslarmichal requested changes

2024-11-16 23:12 UTC, cieslarmichal commented on src/modules/location_data.h
> +{
It should be declared in location.h in include directory

2024-11-16 23:56 UTC, charan-003 reviewed
.

2024-11-16 23:57 UTC, charan-003 commented
i see 2 test cases are failing, where can i check that

2024-11-17 10:52 UTC, cieslarmichal commented
Well its best to run it locally

2024-11-17 10:53 UTC, cieslarmichal commented
If you need any help with running tests let me know, best to reach faker developers is by our discord channel, link in readme

2024-11-17 15:09 UTC, charan-003 commented
@cieslarmichal so there are [  FAILED  ] LocationTest.shouldGenerateCorrectContinentForKnownCountry
[  FAILED  ] LocationTest.shouldReturnUnknownForUnmappedCountry
[  FAILED  ] LocationTest.shouldGenerateRandomContinent

these test cases failing and I'm not sure what's wrong with it

2024-11-18 08:25 UTC, closed without merging