feat: added continents function #984
cieslarmichal/faker-cxx pull request #985
Opened 2024-11-17 23:11 UTC by charan-003

- Added: A new continent() function to determine the continent for a given country.
- Fallback: Implemented a fallback to return "Unknown" for unmapped countries.

- Updates to Codebase:
- Modified location.cpp and location_data.h to include continent-related logic.

- Tests:
- Added tests in location_test.cpp under the new LocationContinentTest suite:
- shouldGenerateCorrectContinentForKnownCountry
- shouldReturnUnknownForUnmappedCountry
- shouldGenerateRandomContinent

2024-11-17 23:28 UTC, cieslarmichal requested changes

2024-11-17 23:28 UTC, cieslarmichal commented on tests/modules/location_test.cpp
> +#include <iostream>
Remove

2024-11-17 23:28 UTC, cieslarmichal commented on include/faker-cxx/location.h
> +FAKER_CXX_EXPORT void validateCountryMapping();
Remove, it should be only continent function in header file added

2024-11-17 23:42 UTC, cieslarmichal requested changes

2024-11-17 23:58 UTC, charan-003 reviewed
removed unused methods

2024-11-18 08:28 UTC, cieslarmichal commented on src/modules/location_data.h
> +
remove comment and empty lines

2024-11-18 08:28 UTC, cieslarmichal commented on src/modules/location.cpp
> +
remove empty lines

2024-11-18 08:29 UTC, cieslarmichal commented on src/modules/location.cpp
> +    //std::cout << "Country Not Found: " << selectedCountry << ", Returning: Unknown" << std::endl;
remove comments please

2024-11-18 08:30 UTC, cieslarmichal commented on include/faker-cxx/location.h
> + * faker::location::continent() // Random continent
replace `Random continent` with actual random continent (any of them)

2024-11-18 21:13 UTC, cieslarmichal approved these changes

2024-11-18 21:15 UTC, charan-003 reviewed
removed comments and empty spaces, also added feature for random continent

2024-11-19 07:30 UTC, cieslarmichal requested changes

2024-11-19 07:30 UTC, cieslarmichal commented on include/faker-cxx/location.h
> + * faker::location::continent()
Write some continent in comment like Africa

2024-11-19 07:30 UTC, cieslarmichal commented on src/modules/location.cpp
> +#include <iostream>
Remove please

2024-11-19 08:02 UTC, charan-003 reviewed
.

2024-11-19 08:07 UTC, cieslarmichal approved these changes

2024-11-19 08:08 UTC, merged